In [26]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
from faker import Faker

fake = Faker()

In [27]:
contract_periods = pd.DataFrame({
        "contract_period_id": range(1, 4), 
        "period": [12, 24, 36]
    })

contract_types = pd.DataFrame({
        "contract_type_id": range(1, 4),
        "contract_type": ["Mobile", "Broadband", "Bundle"]
    })


details_rows = []
n =5
for i in range(n+1):
    created_at = fake.date_time_between(start_date="-3y", end_date="now")
    last_updated = created_at + timedelta(days=np.random.randint(1, 500))

    details_rows.append({
        "contract_details_id": i,
        "contract_title": fake.catch_phrase(),
        "initial_price": round(np.random.uniform(10, 200), 2),
        "discount_percent": round(np.random.choice([0, 5, 10, 15, 20]), 1),
        "contract_period_id": np.random.choice(contract_periods["contract_period_id"]),
        "num_of_sims": np.random.randint(1, 5),
        "num_of_devices": np.random.randint(0, 3),
        "personal_data_id": 1, 
        "created_at": created_at,
        "last_updated": last_updated
    })

    contract_details = pd.DataFrame(details_rows)

contracts_rows = []
for i in range(n+1):
    created_at = contract_details.iloc[i - 1]["created_at"]
    last_updated = contract_details.iloc[i - 1]["last_updated"]

    contracts_rows.append({
        "contract_id": i,
        "contract_details_id": i,
        "contract_type_id": np.random.choice(contract_types["contract_type_id"]),
        "created_at": created_at,
        "last_updated": last_updated
    })

contracts = pd.DataFrame(contracts_rows)

In [28]:
df = contract_details

df

,contract_details_id,contract_title,initial_price,discount_percent,contract_period_id,num_of_sims,num_of_devices,personal_data_id,created_at,last_updated
0,0,Total tertiary portal,30.37,0,2,4,0,1,2024-08-19 04:20:14.610804,2025-11-24 04:20:14.610804
1,1,Proactive user-facing productivity,199.78,5,3,4,2,1,2022-12-11 18:31:10.977015,2023-11-28 18:31:10.977015
2,2,Polarized high-level concept,168.18,20,2,1,0,1,2023-03-21 16:26:19.851083,2023-07-29 16:26:19.851083
3,3,Up-sized tertiary success,91.40,5,2,3,0,1,2025-07-09 09:54:16.886601,2025-09-29 09:54:16.886601
4,4,Fully-configurable intermediate monitoring,74.19,10,2,1,0,1,2024-04-01 05:04:09.387599,2024-04-14 05:04:09.387599
5,5,Integrated upward-trending superstructure,160.30,15,3,2,1,1,2025-07-23 07:38:37.926804,2026-07-22 07:38:37.926804

In [29]:
df = df.merge(contract_periods, on="contract_period_id", how="left")
df

,contract_details_id,contract_title,initial_price,discount_percent,contract_period_id,num_of_sims,num_of_devices,personal_data_id,created_at,last_updated,period
0,0,Total tertiary portal,30.37,0,2,4,0,1,2024-08-19 04:20:14.610804,2025-11-24 04:20:14.610804,24
1,1,Proactive user-facing productivity,199.78,5,3,4,2,1,2022-12-11 18:31:10.977015,2023-11-28 18:31:10.977015,36
2,2,Polarized high-level concept,168.18,20,2,1,0,1,2023-03-21 16:26:19.851083,2023-07-29 16:26:19.851083,24
3,3,Up-sized tertiary success,91.40,5,2,3,0,1,2025-07-09 09:54:16.886601,2025-09-29 09:54:16.886601,24
4,4,Fully-configurable intermediate monitoring,74.19,10,2,1,0,1,2024-04-01 05:04:09.387599,2024-04-14 05:04:09.387599,24
5,5,Integrated upward-trending superstructure,160.30,15,3,2,1,1,2025-07-23 07:38:37.926804,2026-07-22 07:38:37.926804,36

In [30]:
df = df.merge(contracts, on="contract_details_id", how="left")
df

,contract_details_id,contract_title,initial_price,discount_percent,contract_period_id,num_of_sims,num_of_devices,personal_data_id,created_at_x,last_updated_x,period,contract_id,contract_type_id,created_at_y,last_updated_y
0,0,Total tertiary portal,30.37,0,2,4,0,1,2024-08-19 04:20:14.610804,2025-11-24 04:20:14.610804,24,0,1,2025-07-23 07:38:37.926804,2026-07-22 07:38:37.926804
1,1,Proactive user-facing productivity,199.78,5,3,4,2,1,2022-12-11 18:31:10.977015,2023-11-28 18:31:10.977015,36,1,2,2024-08-19 04:20:14.610804,2025-11-24 04:20:14.610804
2,2,Polarized high-level concept,168.18,20,2,1,0,1,2023-03-21 16:26:19.851083,2023-07-29 16:26:19.851083,24,2,1,2022-12-11 18:31:10.977015,2023-11-28 18:31:10.977015
3,3,Up-sized tertiary success,91.40,5,2,3,0,1,2025-07-09 09:54:16.886601,2025-09-29 09:54:16.886601,24,3,1,2023-03-21 16:26:19.851083,2023-07-29 16:26:19.851083
4,4,Fully-configurable intermediate monitoring,74.19,10,2,1,0,1,2024-04-01 05:04:09.387599,2024-04-14 05:04:09.387599,24,4,2,2025-07-09 09:54:16.886601,2025-09-29 09:54:16.886601
5,5,Integrated upward-trending superstructure,160.30,15,3,2,1,1,2025-07-23 07:38:37.926804,2026-07-22 07:38:37.926804,36,5,3,2024-04-01 05:04:09.387599,2024-04-14 05:04:09.387599

In [31]:
df = df.merge(contract_types, on="contract_type_id", how="left")

df

,contract_details_id,contract_title,initial_price,discount_percent,contract_period_id,num_of_sims,num_of_devices,personal_data_id,created_at_x,last_updated_x,period,contract_id,contract_type_id,created_at_y,last_updated_y,contract_type
0,0,Total tertiary portal,30.37,0,2,4,0,1,2024-08-19 04:20:14.610804,2025-11-24 04:20:14.610804,24,0,1,2025-07-23 07:38:37.926804,2026-07-22 07:38:37.926804,Mobile
1,1,Proactive user-facing productivity,199.78,5,3,4,2,1,2022-12-11 18:31:10.977015,2023-11-28 18:31:10.977015,36,1,2,2024-08-19 04:20:14.610804,2025-11-24 04:20:14.610804,Broadband
2,2,Polarized high-level concept,168.18,20,2,1,0,1,2023-03-21 16:26:19.851083,2023-07-29 16:26:19.851083,24,2,1,2022-12-11 18:31:10.977015,2023-11-28 18:31:10.977015,Mobile
3,3,Up-sized tertiary success,91.40,5,2,3,0,1,2025-07-09 09:54:16.886601,2025-09-29 09:54:16.886601,24,3,1,2023-03-21 16:26:19.851083,2023-07-29 16:26:19.851083,Mobile
4,4,Fully-configurable intermediate monitoring,74.19,10,2,1,0,1,2024-04-01 05:04:09.387599,2024-04-14 05:04:09.387599,24,4,2,2025-07-09 09:54:16.886601,2025-09-29 09:54:16.886601,Broadband
5,5,Integrated upward-trending superstructure,160.30,15,3,2,1,1,2025-07-23 07:38:37.926804,2026-07-22 07:38:37.926804,36,5,3,2024-04-01 05:04:09.387599,2024-04-14 05:04:09.387599,Bundle

In [32]:
df = df.drop(["contract_details_id", "contract_type_id", "contract_period_id"], axis=1)

df

,contract_title,initial_price,discount_percent,num_of_sims,num_of_devices,personal_data_id,created_at_x,last_updated_x,period,contract_id,created_at_y,last_updated_y,contract_type
0,Total tertiary portal,30.37,0,4,0,1,2024-08-19 04:20:14.610804,2025-11-24 04:20:14.610804,24,0,2025-07-23 07:38:37.926804,2026-07-22 07:38:37.926804,Mobile
1,Proactive user-facing productivity,199.78,5,4,2,1,2022-12-11 18:31:10.977015,2023-11-28 18:31:10.977015,36,1,2024-08-19 04:20:14.610804,2025-11-24 04:20:14.610804,Broadband
2,Polarized high-level concept,168.18,20,1,0,1,2023-03-21 16:26:19.851083,2023-07-29 16:26:19.851083,24,2,2022-12-11 18:31:10.977015,2023-11-28 18:31:10.977015,Mobile
3,Up-sized tertiary success,91.40,5,3,0,1,2025-07-09 09:54:16.886601,2025-09-29 09:54:16.886601,24,3,2023-03-21 16:26:19.851083,2023-07-29 16:26:19.851083,Mobile
4,Fully-configurable intermediate monitoring,74.19,10,1,0,1,2024-04-01 05:04:09.387599,2024-04-14 05:04:09.387599,24,4,2025-07-09 09:54:16.886601,2025-09-29 09:54:16.886601,Broadband
5,Integrated upward-trending superstructure,160.30,15,2,1,1,2025-07-23 07:38:37.926804,2026-07-22 07:38:37.926804,36,5,2024-04-01 05:04:09.387599,2024-04-14 05:04:09.387599,Bundle

In [39]:
df["effective_price"] = np.where(
    df["discount_percent"] > 0,
    df["initial_price"] * (1 - df["discount_percent"]/100),
    df["initial_price"]
).round(2)

df

,contract_title,initial_price,discount_percent,num_of_sims,num_of_devices,personal_data_id,created_at_x,last_updated_x,period,contract_id,created_at_y,last_updated_y,contract_type,effective_price
0,Total tertiary portal,30.37,0,4,0,1,2024-08-19 04:20:14.610804,2025-11-24 04:20:14.610804,24,0,2025-07-23 07:38:37.926804,2026-07-22 07:38:37.926804,Mobile,30.37
1,Proactive user-facing productivity,199.78,5,4,2,1,2022-12-11 18:31:10.977015,2023-11-28 18:31:10.977015,36,1,2024-08-19 04:20:14.610804,2025-11-24 04:20:14.610804,Broadband,189.79
2,Polarized high-level concept,168.18,20,1,0,1,2023-03-21 16:26:19.851083,2023-07-29 16:26:19.851083,24,2,2022-12-11 18:31:10.977015,2023-11-28 18:31:10.977015,Mobile,134.54
3,Up-sized tertiary success,91.40,5,3,0,1,2025-07-09 09:54:16.886601,2025-09-29 09:54:16.886601,24,3,2023-03-21 16:26:19.851083,2023-07-29 16:26:19.851083,Mobile,86.83
4,Fully-configurable intermediate monitoring,74.19,10,1,0,1,2024-04-01 05:04:09.387599,2024-04-14 05:04:09.387599,24,4,2025-07-09 09:54:16.886601,2025-09-29 09:54:16.886601,Broadband,66.77
5,Integrated upward-trending superstructure,160.30,15,2,1,1,2025-07-23 07:38:37.926804,2026-07-22 07:38:37.926804,36,5,2024-04-01 05:04:09.387599,2024-04-14 05:04:09.387599,Bundle,136.26